// AUTO-GENERATED by tools/packActionButtons.mjs — do not edit by hand.
// Regenerate after adding/changing action button icons: npm run pack:action-buttons

export const ACTION_BUTTON_ATLAS_FILE = 'action-buttons-atlas.png';
export const ACTION_BUTTON_ATLAS_CELL = 120;
export const ACTION_BUTTON_ATLAS_COLS = 5;
export const ACTION_BUTTON_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
  'action-build': { x: 0, y: 0 },
  'action-build-bridge': { x: 120, y: 0 },
  'action-build-mine': { x: 240, y: 0 },
  'action-build-port': { x: 360, y: 0 },
  'action-build-road': { x: 480, y: 0 },
  'action-build-sawmill': { x: 0, y: 120 },
  'action-build-wall': { x: 120, y: 120 },
  'action-capture': { x: 240, y: 120 },
  'action-capture-map': { x: 360, y: 120 },
  'action-cup': { x: 480, y: 120 },
  'action-deal-with-pirates': { x: 0, y: 240 },
  'action-disband': { x: 120, y: 240 },
  'action-end-turn': { x: 240, y: 240 },
  'action-forest-temple': { x: 360, y: 240 },
  'action-get-bonus': { x: 480, y: 240 },
  'action-get-bottle': { x: 0, y: 360 },
  'action-heal': { x: 120, y: 360 },
  'action-ship-upgrade': { x: 240, y: 360 },
  'action-skills': { x: 360, y: 360 },
  'action-spawn': { x: 480, y: 360 },
  'action-spawn-catapult': { x: 0, y: 480 },
  'action-spawn-knight': { x: 120, y: 480 },
  'action-spawn-rider': { x: 240, y: 480 },
  'action-spawn-shield': { x: 360, y: 480 },
  'action-spawn-swordsman': { x: 480, y: 480 },
  'action-spawn-warrior': { x: 0, y: 600 },
  'action-stats': { x: 120, y: 600 },
  'action-upgrade': { x: 240, y: 600 },
  'action-water-temple': { x: 360, y: 600 },
};
