// AUTO-GENERATED by tools/packBuildings.mjs — do not edit by hand.
// Regenerate after adding/changing building tiles: npm run pack:buildings

export const BUILDINGS_ATLAS_FILE = 'buildings-atlas.png';
export const BUILDINGS_ATLAS_CELL_W = 256;
export const BUILDINGS_ATLAS_CELL_H = 448;
export const BUILDINGS_ATLAS_COLS = 6;
export const BUILDINGS_ATLAS_FRAMES: Record<string, { x: number; y: number; w: number; h: number }> = {
  'bridge-ne': { x: 0, y: 0, w: 256, h: 448 },
  'bridge-nw': { x: 256, y: 0, w: 256, h: 448 },
  'bridge-we': { x: 512, y: 0, w: 256, h: 448 },
  'forest-temple-1': { x: 768, y: 0, w: 256, h: 448 },
  'forest-temple-2': { x: 1024, y: 0, w: 256, h: 448 },
  'forest-temple-3': { x: 1280, y: 0, w: 256, h: 448 },
  'forest-temple-4': { x: 0, y: 448, w: 256, h: 448 },
  'mine': { x: 256, y: 448, w: 256, h: 448 },
  'port-e': { x: 512, y: 448, w: 256, h: 448 },
  'port-ne': { x: 768, y: 448, w: 256, h: 448 },
  'port-nw': { x: 1024, y: 448, w: 256, h: 448 },
  'port-se': { x: 1280, y: 448, w: 256, h: 448 },
  'port-sw': { x: 0, y: 896, w: 256, h: 448 },
  'port-w': { x: 256, y: 896, w: 256, h: 448 },
  'sawmill': { x: 512, y: 896, w: 256, h: 448 },
  'village-empty': { x: 768, y: 896, w: 256, h: 448 },
  'wall': { x: 1024, y: 896, w: 256, h: 448 },
  'water-temple-1': { x: 1280, y: 896, w: 256, h: 448 },
  'water-temple-2': { x: 0, y: 1344, w: 256, h: 448 },
  'water-temple-3': { x: 256, y: 1344, w: 256, h: 448 },
  'water-temple-4': { x: 512, y: 1344, w: 256, h: 448 },
};
