// AUTO-GENERATED by tools/packIcons16.mjs — do not edit by hand.
// Regenerate after adding/changing 16px icons: npm run pack:icons-16

export const ICONS16_ATLAS_FILE = 'icons-16-atlas.png';
export const ICONS16_ATLAS_CELL = 16;
export const ICONS16_ATLAS_COLS = 7;
export const ICONS16_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
  'attack-16': { x: 0, y: 0 },
  'def-16': { x: 16, y: 0 },
  'gold-16': { x: 32, y: 0 },
  'help-16': { x: 48, y: 0 },
  'hp-16': { x: 64, y: 0 },
  'move-16': { x: 80, y: 0 },
  'village-16': { x: 96, y: 0 },
};
