// AUTO-GENERATED by tools/packIcons32.mjs — do not edit by hand.
// Regenerate after adding/changing 32px icons: npm run pack:icons-32

export const ICONS32_ATLAS_FILE = 'icons-32-atlas.png';
export const ICONS32_ATLAS_CELL = 32;
export const ICONS32_ATLAS_COLS = 4;
export const ICONS32_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
  'forest-protection-32': { x: 0, y: 0 },
  'gold-32': { x: 32, y: 0 },
  'ore-32': { x: 64, y: 0 },
  'stone-32': { x: 96, y: 0 },
  'village-connected-32': { x: 0, y: 32 },
  'water-protection-32': { x: 32, y: 32 },
  'wood-32': { x: 64, y: 32 },
};
