// AUTO-GENERATED by tools/packTerrain.mjs — do not edit by hand.
// Regenerate after adding/changing terrain tiles: npm run pack:terrain

export const TERRAIN_ATLAS_FILE = 'terrain-atlas.png';
export const TERRAIN_ATLAS_CELL_W = 256;
export const TERRAIN_ATLAS_CELL_H = 448;
export const TERRAIN_ATLAS_COLS = 6;
export const TERRAIN_ATLAS_FRAMES: Record<string, { x: number; y: number; w: number; h: number }> = {
  'desert-forest': { x: 0, y: 0, w: 256, h: 448 },
  'desert-land': { x: 256, y: 0, w: 256, h: 448 },
  'desert-mountain': { x: 512, y: 0, w: 256, h: 448 },
  'fog': { x: 768, y: 0, w: 256, h: 448 },
  'grassland-forest': { x: 1024, y: 0, w: 256, h: 448 },
  'grassland-land': { x: 1280, y: 0, w: 256, h: 448 },
  'grassland-mountain': { x: 0, y: 448, w: 256, h: 448 },
  'rainforest-forest': { x: 256, y: 448, w: 256, h: 448 },
  'rainforest-land': { x: 512, y: 448, w: 256, h: 448 },
  'rainforest-mountain': { x: 768, y: 448, w: 256, h: 448 },
  'taiga-forest': { x: 1024, y: 448, w: 256, h: 448 },
  'taiga-land': { x: 1280, y: 448, w: 256, h: 448 },
  'taiga-mountain': { x: 0, y: 896, w: 256, h: 448 },
  'tundra-forest': { x: 256, y: 896, w: 256, h: 448 },
  'tundra-land': { x: 512, y: 896, w: 256, h: 448 },
  'tundra-mountain': { x: 768, y: 896, w: 256, h: 448 },
  'water': { x: 1024, y: 896, w: 256, h: 448 },
};
