// AUTO-GENERATED by tools/packTerrainBiomes.mjs — do not edit by hand.
// Regenerate after adding/changing biome terrain tiles: npm run pack:terrain-biomes

export type TerrainBiomeFrame = { x: number; y: number; w: number; h: number };
export interface TerrainBiomeAtlas {
  file: string;
  cellW: number;
  cellH: number;
  frames: Record<string, TerrainBiomeFrame>;
}

export const TERRAIN_BIOME_ATLASES: Record<string, TerrainBiomeAtlas> = {
  grassland: {
    file: 'terrain-grassland-atlas.png',
    cellW: 256,
    cellH: 448,
    frames: {
      'grassland-forest-autumn': { x: 0, y: 0, w: 256, h: 448 },
      'grassland-forest-spring': { x: 256, y: 0, w: 256, h: 448 },
      'grassland-forest-summer': { x: 512, y: 0, w: 256, h: 448 },
      'grassland-forest-winter': { x: 0, y: 448, w: 256, h: 448 },
      'grassland-land-autumn': { x: 256, y: 448, w: 256, h: 448 },
      'grassland-land-spring': { x: 512, y: 448, w: 256, h: 448 },
      'grassland-land-summer': { x: 0, y: 896, w: 256, h: 448 },
      'grassland-land-winter': { x: 256, y: 896, w: 256, h: 448 },
      'grassland-mountain-spring': { x: 512, y: 896, w: 256, h: 448 },
    },
  },
  desert: {
    file: 'terrain-desert-atlas.png',
    cellW: 256,
    cellH: 448,
    frames: {
      'desert-forest-spring': { x: 0, y: 0, w: 256, h: 448 },
      'desert-land-spring': { x: 256, y: 0, w: 256, h: 448 },
      'desert-mountain-spring': { x: 512, y: 0, w: 256, h: 448 },
    },
  },
  tundra: {
    file: 'terrain-tundra-atlas.png',
    cellW: 256,
    cellH: 448,
    frames: {
      'tundra-forest-autumn': { x: 0, y: 0, w: 256, h: 448 },
      'tundra-forest-spring': { x: 256, y: 0, w: 256, h: 448 },
      'tundra-forest-summer': { x: 512, y: 0, w: 256, h: 448 },
      'tundra-forest-winter': { x: 0, y: 448, w: 256, h: 448 },
      'tundra-land-autumn': { x: 256, y: 448, w: 256, h: 448 },
      'tundra-land-spring': { x: 512, y: 448, w: 256, h: 448 },
      'tundra-land-summer': { x: 0, y: 896, w: 256, h: 448 },
      'tundra-land-winter': { x: 256, y: 896, w: 256, h: 448 },
      'tundra-mountain-spring': { x: 512, y: 896, w: 256, h: 448 },
    },
  },
  taiga: {
    file: 'terrain-taiga-atlas.png',
    cellW: 256,
    cellH: 448,
    frames: {
      'taiga-forest-autumn': { x: 0, y: 0, w: 256, h: 448 },
      'taiga-forest-spring': { x: 256, y: 0, w: 256, h: 448 },
      'taiga-forest-summer': { x: 512, y: 0, w: 256, h: 448 },
      'taiga-forest-winter': { x: 0, y: 448, w: 256, h: 448 },
      'taiga-land-autumn': { x: 256, y: 448, w: 256, h: 448 },
      'taiga-land-spring': { x: 512, y: 448, w: 256, h: 448 },
      'taiga-land-summer': { x: 0, y: 896, w: 256, h: 448 },
      'taiga-land-winter': { x: 256, y: 896, w: 256, h: 448 },
      'taiga-mountain-spring': { x: 512, y: 896, w: 256, h: 448 },
    },
  },
  rainforest: {
    file: 'terrain-rainforest-atlas.png',
    cellW: 256,
    cellH: 448,
    frames: {
      'rainforest-forest-spring': { x: 0, y: 0, w: 256, h: 448 },
      'rainforest-land-spring': { x: 256, y: 0, w: 256, h: 448 },
      'rainforest-mountain-spring': { x: 512, y: 0, w: 256, h: 448 },
    },
  },
};
