// AUTO-GENERATED by tools/packVillageTribes.mjs — do not edit by hand.
// Regenerate after adding/changing village-barbarians tiles: npm run pack:village-barbarians

export const VILLAGE_BARBARIANS_ATLAS_FILE = 'village-barbarians-atlas.png';
export const VILLAGE_BARBARIANS_ATLAS_CELL_W = 90;
export const VILLAGE_BARBARIANS_ATLAS_CELL_H = 90;
export const VILLAGE_BARBARIANS_ATLAS_COLS = 5;
export const VILLAGE_BARBARIANS_ATLAS_FRAMES: Record<string, { x: number; y: number; w: number; h: number }> = {
  'm1': { x: 0, y: 0, w: 90, h: 90 },
  'm2': { x: 90, y: 0, w: 90, h: 90 },
  'm3': { x: 180, y: 0, w: 90, h: 90 },
  'm4': { x: 270, y: 0, w: 90, h: 90 },
  't1': { x: 360, y: 0, w: 90, h: 90 },
};
