export enum AiActionType {
  UPGRADE = 'upgrade',
  MOVE = 'move',
  ATTACK = 'attack',
  STUN = 'stun',
  SPAWN = 'spawn',
  CAPTURE = 'capture',
  HEAL = 'heal',
  BUILD = 'build',
  BUILD_ROAD = 'buildRoad',
  BUILD_BRIDGE = 'buildBridge',
  UPGRADE_SHIP = 'upgradeShip',
  ENABLE_STEALTH = 'enableStealth',
  STORM = 'storm',
  TRAP = 'trap',
  BURN = 'burn',
  BURN_ROAD = 'burnRoad',
  BUILDER_BUILD = 'builderBuild',
  OPEN_SKILL = 'openSkill',
}
