export enum OverlayKind {
  SPAWN = 'spawn',
  SKILL = 'skill',
  STATS = 'stats',
  ACHIEVEMENTS = 'achievements',
  WELCOME = 'welcome',
  LEAVE = 'leave',
  UNIT_HELP = 'unitHelp',
  SETTLEMENT_HELP = 'settlementHelp',
  BUILDING_HELP = 'buildingHelp',
  BUILDING_LIMIT_HELP = 'buildingLimitHelp',
  BRIDGE_HELP = 'bridgeHelp',
  SHIP_LANDING = 'shipLanding',
  MOVE_ATTACK = 'moveAttack',
  STALKER_REVEAL = 'stalkerReveal',
  STUN_CHOICE = 'stunChoice',
  BONUS_LEAVE = 'bonusLeave',
  BUILDER_BUILD = 'builderBuild',
  THORN_TRAP = 'thornTrap',
  DISBAND = 'disband',
  WATCHING_PROMPT = 'watchingPrompt',
}
