export enum SkillId {
  CLIMBING = 'climbing',
  SMITHERY = 'smithery',
  SWORDSMAN = 'swordsman',
  GEOLOGY = 'geology',
  WATER = 'water',
  NAVIGATION = 'navigation',
  WATER_TEMPLES = 'waterTemples',
  FORESTRY = 'forestry',
  FOREST_TEMPLE = 'forestTemple',
  SCIENCE = 'science',
  ROADS = 'roads',
  SHIELDS = 'shields',
  DEFENSE = 'defense',
  CATAPULT = 'catapult',
  RIDING = 'riding',
  KNIGHTS = 'knights',
  AGRICULTURE = 'agriculture',
  GRANARY = 'granary',
  BRIDGES = 'bridges',
}
