export enum TutorialStepId {
  WELCOME = 'welcome',
  MOVE_UNIT = 'moveUnit',
  UPGRADE_VILLAGE = 'upgradeVillage',
  OPEN_FORESTRY = 'openForestry',
  END_TURN1 = 'endTurn1',
  END_TURN2 = 'endTurn2',
  BUILD_SAWMILL = 'buildSawmill',
  OPEN_CLIMBING_SMITHERY = 'openClimbingSmithery',
  BUILD_MINE = 'buildMine',
  SPAWN_ARCHER = 'spawnArcher',
  ATTACK_ENEMY = 'attackEnemy',
  UPGRADE_VILLAGE3 = 'upgradeVillage3',
  OPEN_WATER_NAVIGATION = 'openWaterNavigation',
  BUILD_PORT = 'buildPort',
  BOARD_SHIP = 'boardShip',
  UPGRADE_SHIP = 'upgradeShip',
  ATTACK_ENEMY_SHIP = 'attackEnemyShip',
  COLLECT_BONUS = 'collectBonus',
  APPROACH_FREE_VILLAGE = 'approachFreeVillage',
  CAPTURE_FREE_VILLAGE = 'captureFreeVillage',
  END = 'end',
}
