// Shared packer for the village composite tribe atlases. Each tribe's 90x90
// block PNGs (src/assets/village-<tribe>/*.png: t1 + m1..m4) are packed into a
// single compressed atlas PNG plus a generated manifest with per-tribe constants.
// Run with: npm run pack:village-villagers / npm run pack:village-warriors
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { URL } from 'node:url';
import { decodePng, encodePng, finalizeAtlas } from './packSkills.mjs';

const TRIBE_CONFIGS = {
  cats: { cols: 5, atlasFile: 'village-cats-atlas.png' },
  villagers: { cols: 5, atlasFile: 'village-villagers-atlas.png' },
  warriors: { cols: 5, atlasFile: 'village-warriors-atlas.png' },
  aqua: { cols: 5, atlasFile: 'village-aqua-atlas.png' },
  forest: { cols: 5, atlasFile: 'village-forest-atlas.png' },
  sand: { cols: 5, atlasFile: 'village-sand-atlas.png' },
  barbarians: { cols: 5, atlasFile: 'village-barbarians-atlas.png' },
};

export function tribeSourceUrl(tribe) {
  return new URL(`../src/assets/village-${tribe}/`, import.meta.url);
}

export function tribeAtlasUrl(tribe) {
  return new URL(`../public/textures/village-${tribe}-atlas.png`, import.meta.url);
}

export function tribeManifestUrl(tribe) {
  return new URL(`../src/game/village-${tribe}-atlas-data.gen.ts`, import.meta.url);
}

export function tribeAtlasFileName(tribe) {
  return TRIBE_CONFIGS[tribe].atlasFile;
}

export function tribeCols(tribe) {
  return TRIBE_CONFIGS[tribe].cols;
}

/** Permanent, sorted order of a tribe's source PNG base names (e.g. 'warriors-r-m2'). */
export function tribeOrder(tribe, sourceDir = tribeSourceUrl(tribe)) {
  return readdirSync(sourceDir)
    .filter((n) => n.endsWith('.png'))
    .map((n) => n.slice(0, -'.png'.length))
    .sort();
}

export function generateVillageTribeAtlas(tribe, sourceDir = tribeSourceUrl(tribe), cols = tribeCols(tribe)) {
  const order = readdirSync(sourceDir)
    .filter((n) => n.endsWith('.png'))
    .map((n) => n.slice(0, -'.png'.length))
    .sort();
  const decoded = order.map((base) => ({
    base,
    img: decodePng(readFileSync(new URL(`${base}.png`, sourceDir))),
  }));
  const cellW = decoded[0]?.img.width ?? 0;
  const cellH = decoded[0]?.img.height ?? 0;
  for (const d of decoded) {
    if (d.img.width !== cellW || d.img.height !== cellH) {
      throw new Error(`${d.base}.png must be ${cellW}x${cellH} like the other village-${tribe} tiles, got ${d.img.width}x${d.img.height}`);
    }
  }
  const rows = Math.ceil(decoded.length / cols);
  const width = cols * cellW;
  const height = rows * cellH;
  const rgba = Buffer.alloc(width * height * 4); // zero = fully transparent
  const frames = {};

  decoded.forEach((d, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = col * cellW;
    const y = row * cellH;
    for (let yy = 0; yy < cellH; yy++) {
      d.img.rgba.copy(rgba, (y + yy) * width * 4 + x * 4, yy * cellW * 4, (yy + 1) * cellW * 4);
    }
    frames[d.base] = { x, y, w: cellW, h: cellH };
  });

  const entries = order
    .map((base) => `  '${base}': { x: ${frames[base].x}, y: ${frames[base].y}, w: ${frames[base].w}, h: ${frames[base].h} },`)
    .join('\n');
  const upper = tribe.toUpperCase();
  const manifestTs = `// AUTO-GENERATED by tools/packVillageTribes.mjs — do not edit by hand.
// Regenerate after adding/changing village-${tribe} tiles: npm run pack:village-${tribe}

export const VILLAGE_${upper}_ATLAS_FILE = '${TRIBE_CONFIGS[tribe].atlasFile}';
export const VILLAGE_${upper}_ATLAS_CELL_W = ${cellW};
export const VILLAGE_${upper}_ATLAS_CELL_H = ${cellH};
export const VILLAGE_${upper}_ATLAS_COLS = ${cols};
export const VILLAGE_${upper}_ATLAS_FRAMES: Record<string, { x: number; y: number; w: number; h: number }> = {
${entries}
};
`;

  return {
    png: encodePng(rgba, width, height),
    manifestTs,
    frames,
    width,
    height,
    cellW,
    cellH,
    cols,
    rgba,
  };
}

export async function writeVillageTribeAtlas(tribe) {
  const out = generateVillageTribeAtlas(tribe);
  const png = await finalizeAtlas(out.png);
  writeFileSync(tribeAtlasUrl(tribe), png);
  writeFileSync(tribeManifestUrl(tribe), out.manifestTs);
  return { ...out, png };
}

export async function runPack(tribe) {
  const out = await writeVillageTribeAtlas(tribe);
  console.log(`packed ${Object.keys(out.frames).length} village-${tribe} tiles -> ${out.width}x${out.height} atlas (${out.png.length} bytes)`);
  console.log(`wrote ${tribeAtlasUrl(tribe).pathname}`);
  console.log(`wrote ${tribeManifestUrl(tribe).pathname}`);
}