// Packs each tribe's unit/buildings PNGs (src/assets/tribe-<code>/*.png) into a
// per-tribe compressed atlas PNG plus one generated manifest. The source files
// are never modified. Run with: npm run pack:tribes
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { URL } from 'node:url';
import { decodePng, encodePng, finalizeAtlas } from './packSkills.mjs';

export const SOURCE_ROOT_URL = new URL('../src/assets/', import.meta.url);
export const ATLAS_DIR_URL = new URL('../public/textures/', import.meta.url);
export const MANIFEST_URL = new URL('../src/game/tribe-atlas-data.gen.ts', import.meta.url);

export const TRIBE_COLS = 6;

/** The playable tribe codes, matching TRIBES in src/game/tribes.ts. Other
 *  `tribe-*` asset dirs (e.g. tribe-icons) are not tribes and are ignored. */
export const TRIBE_CODES = ['aqua', 'barbarians', 'cats', 'forest', 'villagers', 'warriors'];

export function tribeAssetDirURL(code) {
  return new URL(`tribe-${code}/`, SOURCE_ROOT_URL);
}

/** Per-tribe atlas file names (e.g. 'cats' -> 'cats-atlas.png'). */
export const TRIBE_ATLAS_FILES = Object.fromEntries(
  TRIBE_CODES.map((code) => [code, `${code}-atlas.png`]),
);

export function generateTribeAtlas(code, cols = TRIBE_COLS) {
  const sourceDir = tribeAssetDirURL(code);
  const order = readdirSync(sourceDir)
    .filter((n) => n.endsWith('.png'))
    .map((n) => n.slice(0, -'.png'.length))
    .sort();
  const decoded = order.map((base) => ({
    base,
    img: decodePng(readFileSync(new URL(`${base}.png`, sourceDir))),
  }));
  const cellW = decoded[0]?.img.width ?? 0;
  const cellH = decoded[0]?.img.height ?? 0;
  for (const d of decoded) {
    if (d.img.width !== cellW || d.img.height !== cellH) {
      throw new Error(`${code}/${d.base}.png must be ${cellW}x${cellH} like the other tribe tiles, got ${d.img.width}x${d.img.height}`);
    }
  }
  const rows = Math.ceil(decoded.length / cols);
  const width = cols * cellW;
  const height = rows * cellH;
  const rgba = Buffer.alloc(width * height * 4);
  const frames = {};

  decoded.forEach((d, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = col * cellW;
    const y = row * cellH;
    for (let yy = 0; yy < cellH; yy++) {
      d.img.rgba.copy(rgba, (y + yy) * width * 4 + x * 4, yy * cellW * 4, (yy + 1) * cellW * 4);
    }
    frames[d.base] = { x, y, w: cellW, h: cellH };
  });

  return { code, png: encodePng(rgba, width, height), frames, width, height, cellW, cellH, cols };
}

export function generateTribesManifest() {
  const perTribe = TRIBE_CODES.map(
    (code) => `  '${code}': {\n${Object.entries(generateTribeAtlas(code).frames)
      .map(([base, f]) => `    '${base}': { x: ${f.x}, y: ${f.y}, w: ${f.w}, h: ${f.h} },`)
      .join('\n')}\n  },`,
  ).join('\n');
  const files = TRIBE_CODES.map((code) => `  '${code}': '${TRIBE_ATLAS_FILES[code]}',`).join('\n');
  return `// AUTO-GENERATED by tools/packTribes.mjs — do not edit by hand.
// Regenerate after adding/changing tribe tiles: npm run pack:tribes

export const TRIBE_ATLAS_FILES: Record<string, string> = {
${files}
};
export const TRIBE_ATLAS_CELL_W = 256;
export const TRIBE_ATLAS_CELL_H = 448;
export const TRIBE_ATLAS_COLS = ${TRIBE_COLS};
export const TRIBE_ATLAS_FRAMES: Record<string, Record<string, { x: number; y: number; w: number; h: number }>> = {
${perTribe}
};
`;
}

export async function writeTribesAtlas() {
  const manifestTs = generateTribesManifest();
  const pngs = {};
  for (const code of TRIBE_CODES) {
    const final = await finalizeAtlas(generateTribeAtlas(code).png);
    writeFileSync(new URL(TRIBE_ATLAS_FILES[code], ATLAS_DIR_URL), final);
    pngs[code] = final;
  }
  writeFileSync(MANIFEST_URL, manifestTs);
  return { pngs, manifestTs };
}

if (import.meta.main) {
  const out = await writeTribesAtlas();
  const frames = Object.values(out.pngs).reduce((n) => n + 1, 0);
  console.log(`packed ${TRIBE_CODES.map((c) => `${c}:${Object.keys(generateTribeAtlas(c).frames).length}`).join(', ')}`);
  console.log(`wrote ${frames} tribe atlas PNGs to ${ATLAS_DIR_URL.pathname}`);
  console.log(`wrote ${MANIFEST_URL.pathname}`);
}