// Packs the individual achievement icon PNGs (src/assets/achivements/*.png)
// into a single compressed atlas PNG plus a generated manifest. The source
// files are never modified. Run with: npm run pack:achievements
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { URL } from 'node:url';
import { decodePng, encodePng } from './packSkills.mjs';

export const SOURCE_DIR_URL = new URL('../src/assets/achivements/', import.meta.url);
export const ATLAS_URL = new URL('../public/textures/achievements-atlas.png', import.meta.url);
export const MANIFEST_URL = new URL('../src/game/achievementAtlasData.gen.ts', import.meta.url);

export const ACHIEVEMENT_COLS = 3;
export const ACHIEVEMENT_CELL = 164;
export const ACHIEVEMENT_ATLAS_FILE = 'achievements-atlas.png';

/** Permanent, sorted order of the source icon base names (e.g. 'achievement-explorer'). */
export const ACHIEVEMENT_ORDER = readdirSync(SOURCE_DIR_URL)
  .filter((n) => n.endsWith('.png'))
  .map((n) => n.slice(0, -'.png'.length))
  .sort();

export function generateAchievementAtlas(sourceDir = SOURCE_DIR_URL, cols = ACHIEVEMENT_COLS) {
  const order = readdirSync(sourceDir)
    .filter((n) => n.endsWith('.png'))
    .map((n) => n.slice(0, -'.png'.length))
    .sort();
  const cells = order.length;
  const rows = Math.ceil(cells / cols);
  const width = cols * ACHIEVEMENT_CELL;
  const height = rows * ACHIEVEMENT_CELL;
  const rgba = Buffer.alloc(width * height * 4); // zero = fully transparent
  const frames = {};

  order.forEach((base, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = col * ACHIEVEMENT_CELL;
    const y = row * ACHIEVEMENT_CELL;
    const src = readFileSync(new URL(`${base}.png`, sourceDir));
    const icon = decodePng(src);
    if (icon.width !== ACHIEVEMENT_CELL || icon.height !== ACHIEVEMENT_CELL) {
      throw new Error(`${base}.png must be ${ACHIEVEMENT_CELL}x${ACHIEVEMENT_CELL}, got ${icon.width}x${icon.height}`);
    }
    for (let yy = 0; yy < ACHIEVEMENT_CELL; yy++) {
      icon.rgba.copy(rgba, (y + yy) * width * 4 + x * 4, yy * ACHIEVEMENT_CELL * 4, (yy + 1) * ACHIEVEMENT_CELL * 4);
    }
    frames[base] = { x, y, w: ACHIEVEMENT_CELL, h: ACHIEVEMENT_CELL };
  });

  const entries = order
    .map((base) => `  '${base}': { x: ${frames[base].x}, y: ${frames[base].y} },`)
    .join('\n');
  const manifestTs = `// AUTO-GENERATED by tools/packAchievements.mjs — do not edit by hand.
// Regenerate after adding/changing achievement icons: npm run pack:achievements

export const ACHIEVEMENT_ATLAS_FILE = '${ACHIEVEMENT_ATLAS_FILE}';
export const ACHIEVEMENT_ATLAS_CELL = ${ACHIEVEMENT_CELL};
export const ACHIEVEMENT_ATLAS_COLS = ${ACHIEVEMENT_COLS};
export const ACHIEVEMENT_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
${entries}
};
`;

  return {
    png: encodePng(rgba, width, height),
    manifestTs,
    frames,
    width,
    height,
    cell: ACHIEVEMENT_CELL,
    cols,
  };
}

export function writeAchievementAtlas() {
  const out = generateAchievementAtlas();
  writeFileSync(ATLAS_URL, out.png);
  writeFileSync(MANIFEST_URL, out.manifestTs);
  return out;
}

if (import.meta.main) {
  const out = writeAchievementAtlas();
  console.log(`packed ${Object.keys(out.frames).length} achievement icons -> ${out.width}x${out.height} atlas (${out.png.length} bytes)`);
  console.log(`wrote ${ATLAS_URL.pathname}`);
  console.log(`wrote ${MANIFEST_URL.pathname}`);
}