// Packs each biome's seasonal terrain PNGs (src/assets/terrain-<biome>/*.png)
// into its own compressed atlas PNG plus one generated manifest covering all
// biomes. The source files are never modified. Run with: npm run pack:terrain-biomes
import { writeFileSync, readdirSync } from 'node:fs';
import { URL } from 'node:url';
import { finalizeAtlas } from './packSkills.mjs';
import { generateTerrainAtlas } from './packTerrain.mjs';

export const TERRAIN_BIOMES = ['grassland', 'desert', 'tundra', 'taiga', 'rainforest'];
export const TERRAIN_BIOME_COLS = 3;
export const MANIFEST_URL = new URL('../src/atlas-data/terrain-biomes-data.gen.ts', import.meta.url);

export const biomeSourceUrl = (biome) => new URL(`../src/assets/terrain-${biome}/`, import.meta.url);
export const biomeAtlasFile = (biome) => `terrain-${biome}-atlas.png`;
export const biomeAtlasUrl = (biome) => new URL(`../public/textures/${biomeAtlasFile(biome)}`, import.meta.url);

/** Sorted base names of the source PNGs of a biome (e.g. 'grassland-land-spring'). */
export function biomeOrder(biome) {
  return readdirSync(biomeSourceUrl(biome))
    .filter((n) => n.endsWith('.png'))
    .map((n) => n.slice(0, -'.png'.length))
    .sort();
}

export function generateBiomeAtlas(biome, sourceDir = biomeSourceUrl(biome), cols = TERRAIN_BIOME_COLS) {
  return generateTerrainAtlas(sourceDir, cols);
}

export function generateBiomesManifest(atlases) {
  const blocks = TERRAIN_BIOMES.map((biome) => {
    const { frames, cellW, cellH } = atlases[biome];
    const entries = Object.keys(frames)
      .sort()
      .map((k) => `    '${k}': { x: ${frames[k].x}, y: ${frames[k].y}, w: ${frames[k].w}, h: ${frames[k].h} },`)
      .join('\n');
    return `  ${biome}: {
    file: '${biomeAtlasFile(biome)}',
    cellW: ${cellW},
    cellH: ${cellH},
    frames: {
${entries.replace(/^ {4}/gm, '      ')}
    },
  },`;
  }).join('\n');
  return `// AUTO-GENERATED by tools/packTerrainBiomes.mjs — do not edit by hand.
// Regenerate after adding/changing biome terrain tiles: npm run pack:terrain-biomes

export type TerrainBiomeFrame = { x: number; y: number; w: number; h: number };
export interface TerrainBiomeAtlas {
  file: string;
  cellW: number;
  cellH: number;
  frames: Record<string, TerrainBiomeFrame>;
}

export const TERRAIN_BIOME_ATLASES: Record<string, TerrainBiomeAtlas> = {
${blocks}
};
`;
}

export async function writeTerrainBiomeAtlases() {
  const atlases = {};
  for (const biome of TERRAIN_BIOMES) {
    const out = generateBiomeAtlas(biome);
    const png = await finalizeAtlas(out.png);
    writeFileSync(biomeAtlasUrl(biome), png);
    atlases[biome] = { ...out, png };
  }
  writeFileSync(MANIFEST_URL, generateBiomesManifest(atlases));
  return atlases;
}

if (import.meta.main) {
  const atlases = await writeTerrainBiomeAtlases();
  for (const biome of TERRAIN_BIOMES) {
    const a = atlases[biome];
    console.log(`${biome}: ${Object.keys(a.frames).length} tiles -> ${a.width}x${a.height} (${a.png.length} bytes)`);
  }
  console.log(`wrote ${MANIFEST_URL.pathname}`);
}
