// Packs the individual 16px icon PNGs (src/assets/16/*.png) into a single
// compressed one-row atlas PNG plus a generated manifest. The source files are
// never modified. Run with: npm run pack:icons-16
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { URL } from 'node:url';
import { decodePng, encodePng, finalizeAtlas } from './packSkills.mjs';

export const SOURCE_DIR_URL = new URL('../src/assets/16/', import.meta.url);
export const ATLAS_URL = new URL('../public/textures/icons-16-atlas.png', import.meta.url);
export const MANIFEST_URL = new URL('../src/game/icons16AtlasData.gen.ts', import.meta.url);

export const ICONS16_COLS = 7;
export const ICONS16_CELL = 16;
export const ICONS16_ATLAS_FILE = 'icons-16-atlas.png';

/** Permanent, sorted order of the source icon base names (e.g. 'hp-16'). */
export const ICONS16_ORDER = readdirSync(SOURCE_DIR_URL)
  .filter((n) => n.endsWith('.png'))
  .map((n) => n.slice(0, -'.png'.length))
  .sort();

export function generateIcons16Atlas(sourceDir = SOURCE_DIR_URL, cols = ICONS16_COLS) {
  const order = readdirSync(sourceDir)
    .filter((n) => n.endsWith('.png'))
    .map((n) => n.slice(0, -'.png'.length))
    .sort();
  const cells = order.length;
  const rows = Math.ceil(cells / cols);
  const width = cols * ICONS16_CELL;
  const height = rows * ICONS16_CELL;
  const rgba = Buffer.alloc(width * height * 4); // zero = fully transparent
  const frames = {};

  order.forEach((base, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = col * ICONS16_CELL;
    const y = row * ICONS16_CELL;
    const src = readFileSync(new URL(`${base}.png`, sourceDir));
    const icon = decodePng(src);
    if (icon.width !== ICONS16_CELL || icon.height !== ICONS16_CELL) {
      throw new Error(`${base}.png must be ${ICONS16_CELL}x${ICONS16_CELL}, got ${icon.width}x${icon.height}`);
    }
    for (let yy = 0; yy < ICONS16_CELL; yy++) {
      icon.rgba.copy(rgba, (y + yy) * width * 4 + x * 4, yy * ICONS16_CELL * 4, (yy + 1) * ICONS16_CELL * 4);
    }
    frames[base] = { x, y, w: ICONS16_CELL, h: ICONS16_CELL };
  });

  const entries = order
    .map((base) => `  '${base}': { x: ${frames[base].x}, y: ${frames[base].y} },`)
    .join('\n');
  const manifestTs = `// AUTO-GENERATED by tools/packIcons16.mjs — do not edit by hand.
// Regenerate after adding/changing 16px icons: npm run pack:icons-16

export const ICONS16_ATLAS_FILE = '${ICONS16_ATLAS_FILE}';
export const ICONS16_ATLAS_CELL = ${ICONS16_CELL};
export const ICONS16_ATLAS_COLS = ${cols};
export const ICONS16_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
${entries}
};
`;

  return {
    png: encodePng(rgba, width, height),
    manifestTs,
    frames,
    width,
    height,
    cell: ICONS16_CELL,
    cols,
    rgba,
  };
}

export async function writeIcons16Atlas() {
  const out = generateIcons16Atlas();
  const png = await finalizeAtlas(out.png);
  writeFileSync(ATLAS_URL, png);
  writeFileSync(MANIFEST_URL, out.manifestTs);
  return { ...out, png };
}

if (import.meta.main) {
  const out = await writeIcons16Atlas();
  console.log(`packed ${Object.keys(out.frames).length} 16px icons -> ${out.width}x${out.height} atlas (${out.png.length} bytes)`);
  console.log(`wrote ${ATLAS_URL.pathname}`);
  console.log(`wrote ${MANIFEST_URL.pathname}`);
}