// Packs the individual terrain PNGs (src/assets/terrain/*.png) into a single
// compressed atlas PNG plus a generated manifest. The source files are never
// modified. Run with: npm run pack:terrain
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { URL } from 'node:url';
import { decodePng, encodePng, finalizeAtlas } from './packSkills.mjs';

export const SOURCE_DIR_URL = new URL('../src/assets/terrain/', import.meta.url);
export const ATLAS_URL = new URL('../public/textures/terrain-atlas.png', import.meta.url);
export const MANIFEST_URL = new URL('../src/game/terrainAtlasData.gen.ts', import.meta.url);

export const TERRAIN_COLS = 6;
export const TERRAIN_ATLAS_FILE = 'terrain-atlas.png';

/** Permanent, sorted order of the source PNG base names (e.g. 'grassland-land'). */
export const TERRAIN_ORDER = readdirSync(SOURCE_DIR_URL)
  .filter((n) => n.endsWith('.png'))
  .map((n) => n.slice(0, -'.png'.length))
  .sort();

export function generateTerrainAtlas(sourceDir = SOURCE_DIR_URL, cols = TERRAIN_COLS) {
  const order = readdirSync(sourceDir)
    .filter((n) => n.endsWith('.png'))
    .map((n) => n.slice(0, -'.png'.length))
    .sort();
  const decoded = order.map((base) => ({
    base,
    img: decodePng(readFileSync(new URL(`${base}.png`, sourceDir))),
  }));
  const cellW = decoded[0]?.img.width ?? 0;
  const cellH = decoded[0]?.img.height ?? 0;
  for (const d of decoded) {
    if (d.img.width !== cellW || d.img.height !== cellH) {
      throw new Error(`${d.base}.png must be ${cellW}x${cellH} like the other terrain tiles, got ${d.img.width}x${d.img.height}`);
    }
  }
  const rows = Math.ceil(decoded.length / cols);
  const width = cols * cellW;
  const height = rows * cellH;
  const rgba = Buffer.alloc(width * height * 4); // zero = fully transparent
  const frames = {};

  decoded.forEach((d, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = col * cellW;
    const y = row * cellH;
    for (let yy = 0; yy < cellH; yy++) {
      d.img.rgba.copy(rgba, (y + yy) * width * 4 + x * 4, yy * cellW * 4, (yy + 1) * cellW * 4);
    }
    frames[d.base] = { x, y, w: cellW, h: cellH };
  });

  const entries = order
    .map((base) => `  '${base}': { x: ${frames[base].x}, y: ${frames[base].y}, w: ${frames[base].w}, h: ${frames[base].h} },`)
    .join('\n');
  const manifestTs = `// AUTO-GENERATED by tools/packTerrain.mjs — do not edit by hand.
// Regenerate after adding/changing terrain tiles: npm run pack:terrain

export const TERRAIN_ATLAS_FILE = '${TERRAIN_ATLAS_FILE}';
export const TERRAIN_ATLAS_CELL_W = ${cellW};
export const TERRAIN_ATLAS_CELL_H = ${cellH};
export const TERRAIN_ATLAS_COLS = ${cols};
export const TERRAIN_ATLAS_FRAMES: Record<string, { x: number; y: number; w: number; h: number }> = {
${entries}
};
`;

  return {
    png: encodePng(rgba, width, height),
    manifestTs,
    frames,
    width,
    height,
    cellW,
    cellH,
    cols,
    rgba,
  };
}

export async function writeTerrainAtlas() {
  const out = generateTerrainAtlas();
  const png = await finalizeAtlas(out.png);
  writeFileSync(ATLAS_URL, png);
  writeFileSync(MANIFEST_URL, out.manifestTs);
  return { ...out, png };
}

if (import.meta.main) {
  const out = await writeTerrainAtlas();
  console.log(`packed ${Object.keys(out.frames).length} terrain tiles -> ${out.width}x${out.height} atlas (${out.png.length} bytes)`);
  console.log(`wrote ${ATLAS_URL.pathname}`);
  console.log(`wrote ${MANIFEST_URL.pathname}`);
}