// Packs the per-tribe icon PNGs (src/assets/tribe-icons/*.png) into a single
// compressed atlas PNG plus a generated manifest. The source files are never
// modified. Run with: npm run pack:tribe-icons
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { URL } from 'node:url';
import { decodePng, encodePng, finalizeAtlas } from './packSkills.mjs';

export const SOURCE_DIR_URL = new URL('../src/assets/tribe-icons/', import.meta.url);
export const ATLAS_URL = new URL('../public/textures/tribe-icons-atlas.png', import.meta.url);
export const MANIFEST_URL = new URL('../src/game/tribe-icons-atlas-data.gen.ts', import.meta.url);

export const TRIBE_ICON_COLS = 6;
export const TRIBE_ICON_CELL = 120;
export const TRIBE_ICONS_ATLAS_FILE = 'tribe-icons-atlas.png';

/** Permanent, sorted order of the source icon base names (e.g. 'cats-icon'). */
export const TRIBE_ICON_ORDER = readdirSync(SOURCE_DIR_URL)
  .filter((n) => n.endsWith('.png'))
  .map((n) => n.slice(0, -'.png'.length))
  .sort();

export function generateTribeIconsAtlas(sourceDir = SOURCE_DIR_URL, cols = TRIBE_ICON_COLS) {
  const order = readdirSync(sourceDir)
    .filter((n) => n.endsWith('.png'))
    .map((n) => n.slice(0, -'.png'.length))
    .sort();
  const cells = order.length;
  const rows = Math.ceil(cells / cols);
  const width = cols * TRIBE_ICON_CELL;
  const height = rows * TRIBE_ICON_CELL;
  const rgba = Buffer.alloc(width * height * 4); // zero = fully transparent
  const frames = {};

  order.forEach((base, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = col * TRIBE_ICON_CELL;
    const y = row * TRIBE_ICON_CELL;
    const src = readFileSync(new URL(`${base}.png`, sourceDir));
    const icon = decodePng(src);
    if (icon.width !== TRIBE_ICON_CELL || icon.height !== TRIBE_ICON_CELL) {
      throw new Error(`${base}.png must be ${TRIBE_ICON_CELL}x${TRIBE_ICON_CELL}, got ${icon.width}x${icon.height}`);
    }
    for (let yy = 0; yy < TRIBE_ICON_CELL; yy++) {
      icon.rgba.copy(rgba, (y + yy) * width * 4 + x * 4, yy * TRIBE_ICON_CELL * 4, (yy + 1) * TRIBE_ICON_CELL * 4);
    }
    frames[base] = { x, y, w: TRIBE_ICON_CELL, h: TRIBE_ICON_CELL };
  });

  const entries = order
    .map((base) => `  '${base}': { x: ${frames[base].x}, y: ${frames[base].y} },`)
    .join('\n');
  const manifestTs = `// AUTO-GENERATED by tools/packTribeIcons.mjs — do not edit by hand.
// Regenerate after adding/changing tribe icons: npm run pack:tribe-icons

export const TRIBE_ICONS_ATLAS_FILE = '${TRIBE_ICONS_ATLAS_FILE}';
export const TRIBE_ICONS_ATLAS_CELL = ${TRIBE_ICON_CELL};
export const TRIBE_ICONS_ATLAS_COLS = ${cols};
export const TRIBE_ICONS_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
${entries}
};
`;

  return {
    png: encodePng(rgba, width, height),
    manifestTs,
    frames,
    width,
    height,
    cell: TRIBE_ICON_CELL,
    cols,
    rgba,
  };
}

export async function writeTribeIconsAtlas() {
  const out = generateTribeIconsAtlas();
  const png = await finalizeAtlas(out.png);
  writeFileSync(ATLAS_URL, png);
  writeFileSync(MANIFEST_URL, out.manifestTs);
  return { ...out, png };
}

if (import.meta.main) {
  const out = await writeTribeIconsAtlas();
  console.log(`packed ${Object.keys(out.frames).length} tribe icons -> ${out.width}x${out.height} atlas (${out.png.length} bytes)`);
  console.log(`wrote ${ATLAS_URL.pathname}`);
  console.log(`wrote ${MANIFEST_URL.pathname}`);
}