// Packs the individual action button icon PNGs (src/assets/action-buttons/*.png)
// into a single compressed atlas PNG plus a generated manifest. The source
// files are never modified. Run with: npm run pack:action-buttons
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { URL } from 'node:url';
import { decodePng, encodePng, finalizeAtlas } from './packSkills.mjs';

export const SOURCE_DIR_URL = new URL('../src/assets/action-buttons/', import.meta.url);
export const ATLAS_URL = new URL('../public/textures/action-buttons-atlas.png', import.meta.url);
export const MANIFEST_URL = new URL('../src/game/actionButtonAtlasData.gen.ts', import.meta.url);

export const ACTION_BUTTON_COLS = 5;
export const ACTION_BUTTON_CELL = 120;
export const ACTION_BUTTON_ATLAS_FILE = 'action-buttons-atlas.png';

/** Permanent, sorted order of the source icon base names (e.g. 'action-upgrade'). */
export const ACTION_BUTTON_ORDER = readdirSync(SOURCE_DIR_URL)
  .filter((n) => n.endsWith('.png'))
  .map((n) => n.slice(0, -'.png'.length))
  .sort();

export function generateActionButtonAtlas(sourceDir = SOURCE_DIR_URL, cols = ACTION_BUTTON_COLS) {
  const order = readdirSync(sourceDir)
    .filter((n) => n.endsWith('.png'))
    .map((n) => n.slice(0, -'.png'.length))
    .sort();
  const cells = order.length;
  const rows = Math.ceil(cells / cols);
  const width = cols * ACTION_BUTTON_CELL;
  const height = rows * ACTION_BUTTON_CELL;
  const rgba = Buffer.alloc(width * height * 4); // zero = fully transparent
  const frames = {};

  order.forEach((base, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = col * ACTION_BUTTON_CELL;
    const y = row * ACTION_BUTTON_CELL;
    const src = readFileSync(new URL(`${base}.png`, sourceDir));
    const icon = decodePng(src);
    if (icon.width !== ACTION_BUTTON_CELL || icon.height !== ACTION_BUTTON_CELL) {
      throw new Error(`${base}.png must be ${ACTION_BUTTON_CELL}x${ACTION_BUTTON_CELL}, got ${icon.width}x${icon.height}`);
    }
    for (let yy = 0; yy < ACTION_BUTTON_CELL; yy++) {
      icon.rgba.copy(rgba, (y + yy) * width * 4 + x * 4, yy * ACTION_BUTTON_CELL * 4, (yy + 1) * ACTION_BUTTON_CELL * 4);
    }
    frames[base] = { x, y, w: ACTION_BUTTON_CELL, h: ACTION_BUTTON_CELL };
  });

  const entries = order
    .map((base) => `  '${base}': { x: ${frames[base].x}, y: ${frames[base].y} },`)
    .join('\n');
  const manifestTs = `// AUTO-GENERATED by tools/packActionButtons.mjs — do not edit by hand.
// Regenerate after adding/changing action button icons: npm run pack:action-buttons

export const ACTION_BUTTON_ATLAS_FILE = '${ACTION_BUTTON_ATLAS_FILE}';
export const ACTION_BUTTON_ATLAS_CELL = ${ACTION_BUTTON_CELL};
export const ACTION_BUTTON_ATLAS_COLS = ${cols};
export const ACTION_BUTTON_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
${entries}
};
`;

  return {
    png: encodePng(rgba, width, height),
    manifestTs,
    frames,
    width,
    height,
    cell: ACTION_BUTTON_CELL,
    cols,
    rgba,
  };
}

export async function writeActionButtonAtlas() {
  const out = generateActionButtonAtlas();
  const png = await finalizeAtlas(out.png);
  writeFileSync(ATLAS_URL, png);
  writeFileSync(MANIFEST_URL, out.manifestTs);
  return { ...out, png };
}

if (import.meta.main) {
  const out = await writeActionButtonAtlas();
  console.log(`packed ${Object.keys(out.frames).length} action button icons -> ${out.width}x${out.height} atlas (${out.png.length} bytes)`);
  console.log(`wrote ${ATLAS_URL.pathname}`);
  console.log(`wrote ${MANIFEST_URL.pathname}`);
}