// Packs the 32px icons (src/assets/32/*.png) into a single compressed atlas
// PNG plus a generated manifest. The source files are never modified.
// Run with: npm run pack:icons-32
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { URL } from 'node:url';
import { decodePng, encodePng, finalizeAtlas } from './packSkills.mjs';

export const SOURCE_DIR_URL = new URL('../src/assets/32/', import.meta.url);
export const ATLAS_URL = new URL('../public/textures/icons-32-atlas.png', import.meta.url);
export const MANIFEST_URL = new URL('../src/game/icons32AtlasData.gen.ts', import.meta.url);

export const ICONS32_COLS = 4;
export const ICONS32_CELL = 32;
export const ICONS32_ATLAS_FILE = 'icons-32-atlas.png';

/** Permanent, sorted order of the source icon base names (e.g. 'water-protection-32'). */
export const ICONS32_ORDER = readdirSync(SOURCE_DIR_URL)
  .filter((n) => n.endsWith('.png'))
  .map((n) => n.slice(0, -'.png'.length))
  .sort();

export function generateIcons32Atlas(sourceDir = SOURCE_DIR_URL, cols = ICONS32_COLS) {
  const order = readdirSync(sourceDir)
    .filter((n) => n.endsWith('.png'))
    .map((n) => n.slice(0, -'.png'.length))
    .sort();
  const cells = order.length;
  const rows = Math.ceil(cells / cols);
  const width = cols * ICONS32_CELL;
  const height = rows * ICONS32_CELL;
  const rgba = Buffer.alloc(width * height * 4); // zero = fully transparent
  const frames = {};

  order.forEach((base, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = col * ICONS32_CELL;
    const y = row * ICONS32_CELL;
    const src = readFileSync(new URL(`${base}.png`, sourceDir));
    const icon = decodePng(src);
    if (icon.width !== ICONS32_CELL || icon.height !== ICONS32_CELL) {
      throw new Error(`${base}.png must be ${ICONS32_CELL}x${ICONS32_CELL}, got ${icon.width}x${icon.height}`);
    }
    for (let yy = 0; yy < ICONS32_CELL; yy++) {
      icon.rgba.copy(rgba, (y + yy) * width * 4 + x * 4, yy * ICONS32_CELL * 4, (yy + 1) * ICONS32_CELL * 4);
    }
    frames[base] = { x, y, w: ICONS32_CELL, h: ICONS32_CELL };
  });

  const entries = order
    .map((base) => `  '${base}': { x: ${frames[base].x}, y: ${frames[base].y} },`)
    .join('\n');
  const manifestTs = `// AUTO-GENERATED by tools/packIcons32.mjs — do not edit by hand.
// Regenerate after adding/changing 32px icons: npm run pack:icons-32

export const ICONS32_ATLAS_FILE = '${ICONS32_ATLAS_FILE}';
export const ICONS32_ATLAS_CELL = ${ICONS32_CELL};
export const ICONS32_ATLAS_COLS = ${cols};
export const ICONS32_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
${entries}
};
`;

  return {
    png: encodePng(rgba, width, height),
    manifestTs,
    frames,
    width,
    height,
    cell: ICONS32_CELL,
    cols,
    rgba,
  };
}

export async function writeIcons32Atlas() {
  const out = generateIcons32Atlas();
  const png = await finalizeAtlas(out.png);
  writeFileSync(ATLAS_URL, png);
  writeFileSync(MANIFEST_URL, out.manifestTs);
  return { ...out, png };
}

if (import.meta.main) {
  const out = await writeIcons32Atlas();
  console.log(`packed ${Object.keys(out.frames).length} 32px icons -> ${out.width}x${out.height} atlas (${out.png.length} bytes)`);
  console.log(`wrote ${ATLAS_URL.pathname}`);
  console.log(`wrote ${MANIFEST_URL.pathname}`);
}