// AUTO-GENERATED by tools/packAchievements.mjs — do not edit by hand.
// Regenerate after adding/changing achievement icons: npm run pack:achievements

export const ACHIEVEMENT_ATLAS_FILE = 'achievements-atlas.png';
export const ACHIEVEMENT_ATLAS_CELL = 164;
export const ACHIEVEMENT_ATLAS_COLS = 3;
export const ACHIEVEMENT_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
  'achievement-10-kills': { x: 0, y: 0 },
  'achievement-3-ships-killed': { x: 164, y: 0 },
  'achievement-bonus-hunter': { x: 328, y: 0 },
  'achievement-explorer': { x: 0, y: 164 },
  'achievement-great-connector': { x: 164, y: 164 },
  'achievement-nothing-to-learn': { x: 328, y: 164 },
  'achievement-perfect-chain': { x: 0, y: 328 },
  'achievement-pirate-purger': { x: 164, y: 328 },
  'achievement-pirates-lucky-day': { x: 328, y: 328 },
};
