// AUTO-GENERATED by tools/packIcons32.mjs — do not edit by hand.
// Regenerate after adding/changing 32px icons: npm run pack:icons-32

export const ICONS32_ATLAS_FILE = 'icons-32-atlas.png';
export const ICONS32_ATLAS_CELL = 32;
export const ICONS32_ATLAS_COLS = 4;
export const ICONS32_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
  'attack-32': { x: 2, y: 2 },
  'cannonbal-32': { x: 38, y: 2 },
  'close-32': { x: 74, y: 2 },
  'def-32': { x: 110, y: 2 },
  'dots-32': { x: 2, y: 38 },
  'food-32': { x: 38, y: 38 },
  'forest-protection-32': { x: 74, y: 38 },
  'gold-32': { x: 110, y: 38 },
  'help-32': { x: 2, y: 74 },
  'hp-32': { x: 38, y: 74 },
  'move-32': { x: 74, y: 74 },
  'ore-32': { x: 110, y: 74 },
  'skull-32': { x: 2, y: 110 },
  'stone-32': { x: 38, y: 110 },
  'unit-32': { x: 74, y: 110 },
  'village-32': { x: 110, y: 110 },
  'village-connected-32': { x: 2, y: 146 },
  'water-protection-32': { x: 38, y: 146 },
  'wood-32': { x: 74, y: 146 },
};
