// AUTO-GENERATED by tools/packSkills.mjs — do not edit by hand.
// Regenerate after adding/changing skill icons: npm run pack:skills

export const SKILL_ATLAS_FILE = 'skills-atlas.png';
export const SKILL_ATLAS_CELL = 120;
export const SKILL_ATLAS_COLS = 5;
export const SKILL_ATLAS_FRAMES: Record<string, { x: number; y: number }> = {
  'skill-agriculture': { x: 0, y: 0 },
  'skill-agronomy': { x: 120, y: 0 },
  'skill-bridges': { x: 240, y: 0 },
  'skill-catapult': { x: 360, y: 0 },
  'skill-climbing': { x: 480, y: 0 },
  'skill-defense': { x: 0, y: 120 },
  'skill-engineering': { x: 120, y: 120 },
  'skill-forest-temples': { x: 240, y: 120 },
  'skill-forestry': { x: 360, y: 120 },
  'skill-geology': { x: 480, y: 120 },
  'skill-granary': { x: 0, y: 240 },
  'skill-knights': { x: 120, y: 240 },
  'skill-medicine': { x: 240, y: 240 },
  'skill-navigation': { x: 360, y: 240 },
  'skill-riding': { x: 480, y: 240 },
  'skill-roads': { x: 0, y: 360 },
  'skill-science': { x: 120, y: 360 },
  'skill-shields': { x: 240, y: 360 },
  'skill-smithery': { x: 360, y: 360 },
  'skill-swordsman': { x: 480, y: 360 },
  'skill-water': { x: 0, y: 480 },
  'skill-water-temples': { x: 120, y: 480 },
};
